name: "Create PR"
on: 
  push:
    branches:
      - develop  # 올바른 트리거 설정

permissions:
  contents: write
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 또는 ${{ secrets.MY_PAT }}
          branch: auto-pr-branch
          base: main
          title: 'Automated Pull Request'
          body: 'This pull request was automatically created by the GitHub Action.'
