name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build WAR with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Create tomcat/webapps directory
        run: mkdir -p ./tomcat/webapps  # tomcat/webapps 디렉토리 생성

      - name: Move WAR to tomcat/webapps directory
        run: |
          cp target/ROOT.war ./tomcat/webapps/ROOT.war  # ROOT.war 파일을 tomcat/webapps 디렉토리로 복사

      - name: Upload WAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "target/ROOT.war"  # tomcat/webapps 디렉토리에서 WAR 파일을 업로드
          target: "/home/ubuntu/tomcat/webapps/"  # EC2의 대상 경로
          debug: true

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --no-cache -t ranpia/tomcat9:latest -f ./tomcat/Dockerfile ./tomcat  # Dockerfile 경로와 컨텍스트 명시

      - name: Push Docker image
        run: |
          docker push ranpia/tomcat9:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test SSH connectivity
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          ssh -v -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} echo "Success"

      - name: SSH to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/tomcat
            docker-compose pull
            docker-compose up -d
