name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      name: Checkout code
        uses: actions/checkout@v2

      
      name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

      
      name: Log in to Docker Hub
           uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}  # 액세스 토큰 사용

      
      name: Build Docker image
          run: |
            docker build -t ranpia/tomcat9:latest ./tomcat

      
      name: Push Docker image
          run: |
            docker push ranpia/tomcat9:latest
    
  deploy:
    runs-on: ubuntu-latest
    steps:
          
      name: SSH to EC2 and Deploy
            uses: appleboy/scp-action@v0.1.7
            with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{ secrets.EC2_USER }}
              key: ${{ secrets.EC2_SSH_KEY }}
              port: 22
              source: "docker-compose.yml"
              target: "/tomcat"
      
            
      name: SSH to EC2
            uses: appleboy/ssh-action@v0.1.7
            with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{ secrets.EC2_USER }}
              key: ${{ secrets.EC2_SSH_KEY }}
              port: 22
              script: |
                cd /tomcat
                docker-compose pull
                docker-compose up -d
